# Generated by Django 3.1 on 2020-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
                ('carbohydrates', models.PositiveIntegerField()),
                ('cholestrol', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('fiber', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('saturated_fat', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
